apiVersion: v1
kind: Pod
metadata:
   name: kafka-connect
   namespace: kafka-ca1
spec:
   containers:
   - name: kafka-connect
     image: confluentinc/cp-kafka:5.0.1
     command:
       - sh
       - -c
       - "exec tail -f /dev/null"
