---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: zookeeper
  name: zookeeper
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata: 
      labels:  
        app: zookeeper
    spec:
      containers:
      - image: library/zookeeper
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: SERVICE_IP
          value: 10.105.38.223
        - name: SERVICE_PORT
          value: "31000"
