---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka-ca1
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
    - name: zookeeper-port
      nodePort: 31000
      port: 2181
      targetPort: 2181
